#!/usr/bin/env python3

import blacklist
import json

url = "https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt"
print(url + "...")
b = blacklist.Blacklist()
b.read_from_url(url)
iocs = b.to_indicators(source=url, author="abuse.ch", type="hostname",
                       description="Feodo malware")

obj = iocs.dump()

with open("abuse-ch.json", "w") as f:
    f.write(json.dumps(obj, indent=4))
    f.close()

print("abuse-ch.json written.")

