#!/usr/bin/env python3

import facebook
import sys
import json
import time

creds = json.loads(open("facebook-creds").read())
fb = facebook.Facebook(creds["id"], creds["secret"])

for v in sys.argv[1:]:

    t = fb.get_domain_report(sys.argv[1])
    print("-----------", v)
    print(json.dumps(t.to_dict(), indent=4))

