#!/usr/bin/env python3

import json
import openioc
import sys
import os

def do(file, inds):
    id = openioc.IocDefinition()
    id.parse_file(file)
    inds.append(id.to_detector())
    
inds=[]

for dir, subdir, files in os.walk("fireeye"):
    for file in files:
        if file.endswith(".ioc"):
            do(os.path.join(dir, file), inds)

iocs = {
    "version": 3,
    "description": "Trust Networks IOCs",
    "definitions": inds
}

with open("fireeye.json", "w") as f:
    f.write(json.dumps(iocs, indent=4))
    f.close()

print("fireeye.json written.")

