#!/usr/bin/env python3

import urlhaus
import json
import csv
import io

url = "https://urlhaus.abuse.ch/downloads/csv/"

u = urlhaus.UrlHaus()
u.read_from_url(url)

iocs = u.to_detector(source=url, author="urlhaus.abuse.ch",
                     description="Urlhaus malware download")

with open("urlhaus.json", "w") as f:
    f.write(json.dumps(iocs, indent=4))
    f.close()

print("urlhaus.json written.")
